name: OunassCase
options:
  bundleIdPrefix: com.yasinkbas
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "15.0"

configs:
  Dev: debug
  Prod: release

targets:
  Application:
    type: application
    platform: iOS
    sources:
      - path: App
    dependencies:
      - target: ProductList
      - target: ProductDetail
      - target: CommonKit
      - target: DependencyManagerKit
      - target: NetworkManagerKit

      - package: NLab
      - package: UILab
    settings:
      base:
        CONFIGURATION_BUILD_DIR: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    scheme:
      configVariants:
        dev: dev
        prod: prod

# Kits
  CommonKit:
    type: framework
    platform: iOS
    sources:
      - path: Kits/CommonKit
        group: Kits/
    dependencies:
      - package: UILab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.CommonKit
        INFOPLIST_FILE: "Kits/CommonKit/Resources/Info.plist"

  DependencyManagerKit:
    type: framework
    platform: iOS
    sources:
      - path: Kits/DependencyManagerKit
        group: Kits/
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.DependencyManagerKit
        INFOPLIST_FILE: "Kits/DependencyManagerKit/Resources/Info.plist"

  NetworkManagerKit:
    type: framework
    platform: iOS
    sources:
      - path: Kits/NetworkManagerKit
        group: Kits/
    dependencies:
      - package: NLab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.NetworkManagerKit
        INFOPLIST_FILE: "Kits/NetworkManagerKit/Resources/Info.plist"

# Modules
  ProductList:
    type: framework
    platform: iOS
    sources:
      - path: Modules/ProductList
        group: Modules/
    dependencies:
      - target: NetworkManagerKit
      - target: CommonKit
      - target: DependencyManagerKit
      - package: UILab
      - package: NLab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.ProductList
        INFOPLIST_FILE: "Modules/ProductList/Resources/Info.plist"

  ProductDetail:
    type: framework
    platform: iOS
    sources:
      - path: Modules/ProductDetail
        group: Modules/
    dependencies:
      - package: UILab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.ProductDetail
        INFOPLIST_FILE: "Modules/ProductDetail/Resources/Info.plist"

# 3rd parties
packages:
  NLab:
    url: "https://github.com/yasinkbas/NLab"
    from: "1.3.0"
  UILab:
    url: "https://github.com/yasinkbas/UILab"
    from: "0.3.4"