name: OunassCase
options:
  bundleIdPrefix: com.yasinkbas
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "15.0"

configs:
  Dev: debug
  Prod: release

targets:
  Application:
    type: application
    platform: iOS
    sources:
      - path: App
    dependencies:
      - target: ProductListModule
      - target: ProductDetailModule
      - target: CommonKit
      - target: CommonViewKit
      - target: DependencyManagerKit
      - target: NetworkManagerKit

      - package: NLab
      - package: UILab
      - package: SDWebImage
    settings:
      base:
        CONFIGURATION_BUILD_DIR: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
    scheme:
      configVariants:
        dev: dev
        prod: prod

# Kits
  CommonKit:
    type: framework
    platform: iOS
    sources:
      - path: Kits/CommonKit
        group: Kits/
    dependencies:
      - package: UILab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.CommonKit
        INFOPLIST_FILE: "Kits/CommonKit/Resources/Info.plist"
    
  CommonViewKit:
    type: framework
    platform: iOS
    sources:
      - path: Kits/CommonViewKit
        group: Kits/
    dependencies:
      - package: UILab
      - package: SDWebImage
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.CommonViewKit
        INFOPLIST_FILE: "Kits/CommonViewKit/Resources/Info.plist"

  DependencyManagerKit:
    type: framework
    platform: iOS
    sources:
      - path: Kits/DependencyManagerKit
        group: Kits/
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.DependencyManagerKit
        INFOPLIST_FILE: "Kits/DependencyManagerKit/Resources/Info.plist"

  NetworkManagerKit:
    type: framework
    platform: iOS
    sources:
      - path: Kits/NetworkManagerKit
        group: Kits/
    dependencies:
      - package: NLab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.NetworkManagerKit
        INFOPLIST_FILE: "Kits/NetworkManagerKit/Resources/Info.plist"

# Modules
  ProductListModule:
    type: framework
    platform: iOS
    sources:
      - path: Modules/ProductListModule
        group: Modules/
    dependencies:
      - target: NetworkManagerKit
      - target: CommonKit
      - target: CommonViewKit
      - target: DependencyManagerKit
      - package: UILab
      - package: NLab
      - package: SDWebImage
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.ProductListModule
        INFOPLIST_FILE: "Modules/ProductListModule/Resources/Info.plist"
    scheme:
      gatherCoverageData: true
      testTargets:
        - target: ProductListTests
          parallelizable: true
          randomExecutionOrder: true
    
  ProductListModuleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/ProductListModule/
        group: Tests/
    resources:
      - path: Tests/ProductListModule/Resources
        group: Tests/
    dependencies:
      - target: ProductListModule
    settings:
      base:
        INFOPLIST_FILE: "Tests/ProductListModule/Info.plist"
    scheme:
      testPlans:
        - path: Tests/ProductListModule/ProductListTests.xctestplan

  ProductDetailModule:
    type: framework
    platform: iOS
    sources:
      - path: Modules/ProductDetailModule
        group: Modules/
    dependencies:
      - target: NetworkManagerKit
      - target: CommonKit
      - target: CommonViewKit
      - target: DependencyManagerKit
      - package: UILab
      - package: NLab
      - package: SDWebImage
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasinkbas.ProductDetailModule
        INFOPLIST_FILE: "Modules/ProductDetailModule/Resources/Info.plist"

# 3rd parties
packages:
  NLab:
    url: "https://github.com/yasinkbas/NLab"
    from: "1.3.0"
  UILab:
    url: "https://github.com/yasinkbas/UILab"
    from: "0.3.4"
  SDWebImage:
    url: "https://github.com/SDWebImage/SDWebImage.git"
    from: "5.21.0"